---
# tasks file for bigip-add-node
- name: Add a new node with the name {{ node_name }} to BIG IP
  f5networks.f5_modules.bigip_node:
    state: present
    name: "{{ node_name }}"
    address: "{{ node_fqdn }}"
    fqdn_auto_populate: no
    description: "{{ node_desc }}"
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  notify: Save the running configuration of BIG-IP to disk

