---
- name: Remove all ansible inventory nodes from F5 Big IP and Save the running config to disk
  hosts: "{{ ec2_name_tag_choice if (ec2_name_tag_choice is defined and ec2_name_tag_choice != '') else 'all' | default('all') }}"
  gather_facts: false
  tasks:
  - name: Loop over hosts to remove them from nodes
    include_role:
      name: rsoliman.f5_demos.bigip_remove_node
    vars:
      node_name_choice: "{{hostvars[item].inventory_hostname}}"
      node_fqdn_choice: "{{hostvars[item].ansible_host}}"
    #loop: "{{ groups['all'] }}"
    loop: "{{ ansible_play_hosts_all }}"
    run_once: true