---
# tasks file for bigip-add-pool-member
  - name: Add an existing node to a pool as a pool member
    f5networks.f5_modules.bigip_pool_member:
      state: present
      pool: "{{ pool_name }}"
      name: "{{ node_name }}"
      address: "{{ node_fqdn }}"
      partition: "{{ pool_partition }}"
      port: "{{ pool_member_port }}"
      description: "{{ pool_member_desc }}"
      connection_limit: "{{ pool_member_connection_limit }}"
      rate_limit: "{{ pool_member_rate_limit }}"
      ratio: "{{ pool_member_ratio }}"
      provider: "{{ bigip_provider }}"
    delegate_to: localhost
    notify: Save the running configuration of BIG-IP to disk