---
# tasks file for bigip-remove-node
- name: remove node with the name {{ node_name }} from BIG IP
  f5networks.f5_modules.bigip_node:
    state: absent
    name: "{{ node_name }}"
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  notify: Save the running configuration of BIG-IP to disk
